_target_: pytorch_ie.taskmodules.RETextClassificationWithIndicesTaskModule
tokenizer_name_or_path: ???

## Long sequence handling
max_window: ??? # Maximum sequence length, depends on the model (e.g. 512 for BERT)

# see the actual model implementation for all available options and defaults
