_target_: src.serializer.BratSerializer
path: ${paths.prediction_save_dir}

# this needs to be a mapping from annotation layer names
# to what to serialize, i.e. "gold", "prediction", or "both".
# For example:
# layers:
#   labeled_spans: gold
#   binary_relations: prediction
layers: ???
