create_test_split:
  _processor_: pie_datasets.DatasetDict.add_test_split
  # take 10% of the train split as the test split
  test_size: 0.1
  # set a fixed seed to make the splitting reproducible
  seed: 12345
  source_split: train
