# This config on its own does nothing more than conll2003.yaml. However, it can be easily combined with further
# preprocessing configs, see conll2003_select_n.yaml for an example.

_target_: src.utils.execute_pipeline
input:
  _target_: pie_datasets.DatasetDict.load_dataset
  path: dataset_builders/pie/conll2003
  ## to use the script from the HuggingFace Hub instead of the local version
  ## (see https://huggingface.co/datasets/pie/conll2003/commit/9d0c6f5807d53e5266dcf1947e4b6bcdbe499fda):
  # path: pie/conll2003
  # revision: 9d0c6f5807d53e5266dcf1947e4b6bcdbe499fda
