# example call:
# python src/evaluate_documents.py dataset=conll2003 metric=count_entity_labels metric.labels=[PER,ORG,LOC,MISC]

_target_: pytorch_ie.metrics.statistics.LabelCountCollector
title: entity label distribution
field: labeled_spans
labels: INFERRED
show_histogram: true
show_as_markdown: true
document_type: pie_documents.documents.TextDocumentWithLabeledSpans
