_target_: src.metrics.F1Metric
layer: ???
show_as_markdown: true
# labels: ???  # all possible labels. if set, calculate per label metrics
# label_field: label  # field of the annotation that contains the label, default: label. required if label_field is set
