# example call:
# python src/evaluate_documents.py dataset=conll2003 metric=span_coverage_characters

_target_: pie_documents.metrics.SpanCoverageCollector
title: span coverage (characters)
layer: labeled_spans
show_histogram: true
show_as_markdown: true
document_type: pie_documents.documents.TextDocumentWithLabeledSpans
