# example call:
# python src/evaluate_documents.py dataset=conll2003 metric=span_lengths_characters

_target_: pie_datasets.statistics.SpanLengthCollector
title: span lengths (characters)
layer: labeled_spans
show_histogram: true
show_as_markdown: true
document_type: pie_documents.documents.TextDocumentWithLabeledSpans
